// This file may be autogenerated, do not place meaningful code here.
// Use it only to define a list of nc-words (registers) that may appear
// in blocks of the nc-file.
namespace SprutTechnology.SCPostprocessor
{
    ///<summary>A class that defines the nc-file - main output file that should be generated by the postprocessor.</summary>
    public partial class NCFile : TTextNCFile
    {
        ///<summary>The block of the nc-file is an ordered list of nc-words</summary>
        public NCBlock Block;
        ///<summary>auto counting</summary>
        public CountingNCWord BlockN = new CountingNCWord("N{######}0", 1, 1, 1);
        ///<summary>X coordinate of the movement</summary>
        public NumericNCWord X = new NumericNCWord("X{-#####.####}", 0);
        ///<summary>Y coordinate of the movement</summary>
        public NumericNCWord Y = new NumericNCWord("Y{-#####.####}", 0);
        ///<summary></summary>
        public NumericNCWord Z = new NumericNCWord("Z{-#####.####}", 0);
        ///<summary>Text field</summary>
        public TextNCWord Text = new TextNCWord("", "", "");
        public NCFile(): base()
        {
            Block = new NCBlock(
                  this, 
                  BlockN, 
                  X, 
                  Y, 
                  Z, 
                  Text);
            OnInit();
        }
    }
}