// This file may be autogenerated, do not place meaningful code here.
// Use it only to define a list of nc-words (registers) that may appear
// in blocks of the nc-file.
namespace SprutTechnology.SCPostprocessor
{
    ///<summary>A class that defines the nc-file - main output file that should be generated by the postprocessor.</summary>
    public partial class NCFile : TTextNCFile
    {
        ///<summary>The block of the nc-file is an ordered list of nc-words</summary>
        public NCBlock Block;
        ///<summary>X coordinate of the movement</summary>
        public NumericNCWord X = new NumericNCWord("{-####.000}", 0);
        ///<summary>Y coordinate of the movement</summary>
        public NumericNCWord Y = new NumericNCWord(",{-####.000}", 0);
        ///<summary></summary>
        public NumericNCWord Z = new NumericNCWord(",{-####.000}", 0);
        ///<summary></summary>
        public NumericNCWord C_num = new NumericNCWord("C{00000}", 0);
        ///<summary></summary>
        public NumericNCWord C_num2 = new NumericNCWord("C{00000}", 0);
        ///<summary></summary>
        public NumericNCWord EC_num = new NumericNCWord("EC{00000}", 0);
        ///<summary></summary>
        public NumericNCWord UF = new NumericNCWord("UF#(){##}", 0);
        ///<summary></summary>
        public NumericNCWord Rx = new NumericNCWord(",{-####.000}", 0);
        ///<summary></summary>
        public NumericNCWord Ry = new NumericNCWord(",{-####.000}", 0);
        ///<summary></summary>
        public NumericNCWord Rz = new NumericNCWord("{-####.000}", 0);
        ///<summary></summary>
        public NumericNCWord FeedV = new NumericNCWord("V={####.#}", 0);
        ///<summary></summary>
        public NumericNCWord FeedVJ = new NumericNCWord("VJ={-####.#}", 0);
        ///<summary></summary>
        public NumericNCWord S = new NumericNCWord("{-######.}", 0);
        ///<summary></summary>
        public NumericNCWord L = new NumericNCWord(",{-######.}", 0);
        ///<summary></summary>
        public NumericNCWord U = new NumericNCWord(",{-######.}", 0);
        ///<summary></summary>
        public NumericNCWord R = new NumericNCWord(",{-######.}", 0);
        ///<summary></summary>
        public NumericNCWord B = new NumericNCWord(",{-######.}", 0);
        ///<summary></summary>
        public NumericNCWord T = new NumericNCWord(",{-######.}", 0);
        ///<summary></summary>
        public NumericNCWord E1 = new NumericNCWord("{-############.}", 0);
        ///<summary></summary>
        public NumericNCWord E2 = new NumericNCWord(",{-############.}", 0);
        ///<summary></summary>
        public NumericNCWord E3 = new NumericNCWord(",{-############.}", 0);
        ///<summary></summary>
        public NumericNCWord E4 = new NumericNCWord(",{-############.}", 0);
        ///<summary></summary>
        public NumericNCWord E5 = new NumericNCWord(",{-############.}", 0);
        ///<summary></summary>
        public NumericNCWord E6 = new NumericNCWord(",{-############.}", 0);
        ///<summary></summary>
        public NCBlock TextBlock;
        ///<summary></summary>
        public CountingNCWord BlockN = new CountingNCWord("{######}", 0, 1, 1);
        ///<summary></summary>
        public TextNCWord Text = new TextNCWord("", "", "");
        public NCFile(): base()
        {
            Block = new NCBlock(
                  this, 
                  X, 
                  Y, 
                  Z, 
                  C_num, 
                  C_num2, 
                  EC_num, 
                  UF, 
                  Rx, 
                  Ry, 
                  Rz, 
                  FeedV, 
                  FeedVJ, 
                  S, 
                  L, 
                  U, 
                  R, 
                  B, 
                  T, 
                  E1, 
                  E2, 
                  E3, 
                  E4, 
                  E5, 
                  E6);
            TextBlock = new NCBlock(
                      this, 
                      BlockN, 
                      Text);
            OnInit();
        }
    }
}